apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k1yrj8zfh-python
  janus-idp.io/tekton: k1yrj8zfh-python
  backstage.io/kubernetes-id: k1yrj8zfh-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: k1yrj8zfh-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
