apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: k1yrj8zfh-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: k1yrj8zfh-python 
  name: k1yrj8zfh-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: k1yrj8zfh-python 
